### ISSUE TITLE
[29/03/24]: Babel Quarto returns error when multiple `-part` is included in `_quarto.yml`

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/JSquarto#35]
### Description

I try to render multiple localized versions. I use the `part` keyword multiple times within the quarto yml configuration and run `babelquarto::render_book(project_dir)`. This returns an error

#### Expected behaviour

- [ ] *It is expected to generate the html files for the docs in the different languages*

#### Actual behaviour

Babel quarto returns and error this when i run `babelquarto::render_book(project_dir)`

- [ ] It first generates the html files for the main language, but the error only occurs when it attempts to generate the doc for the other languages

### How to reproduce

1. Go to project dir
2. Checkout to `netlify_depl` branch
3. First setup your the project locally 
4. Run `npm i --save` to install the dependencies
5. Run `tsc -b` to transpile to javascript.
6. Run `npm run doc:generate include_localized_versions languages="en,ar,es,fr" --source=dist`
7. Open the project in R studio and follow the steps in their doc until you run `babelquarto::render_book(project_dir)`
8. See error 

### Failure Logs

```
> babelquarto::render_book(project_dir)
[ 1/19] index.md
[ 2/19] chapters/tutorials/contributing/improving_documentation.qmd
[ 3/19] chapters/tutorials/contributing/raising_issues.qmd
[ 4/19] chapters/tutorials/contributing/raising_pr.qmd
[ 5/19] chapters/tutorials/how_to/adding_tutorials.qmd
[ 6/19] chapters/tutorials/how_to/optimizing_workflow.qmd
[ 7/19] chapters/tutorials/how_to/starting_the_project.qmd
[ 8/19] chapters/tutorials/project_structure.qmd
[ 9/19] chapters/tutorials/environment_setup.qmd
[10/19] chapters/tutorials/changelog.qmd
[11/19] chapters/tutorials/localization.qmd
[12/19] chapters/globals/globals.qmd
[13/19] chapters/functional doc/utilities/constructidentifier.qmd
[14/19] chapters/functional doc/utilities/commentsutil.qmd
[15/19] chapters/functional doc/utilities/components.qmd
[16/19] chapters/functional doc/utilities/file.qmd
[17/19] chapters/functional doc/utilities/logger.qmd
[18/19] chapters/functional doc/utilities/parser.qmd
[19/19] chapters/functional doc/utilities/writer.qmd

Output created: _book/index.html

ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 24, columns 5--9) property name part is invalid
23:     - chapters/tutorials/localization.en.qmd
24:   - part: Globals
       ~~~~~
25:     chapters: chapters/globals/globals.en.qmd
ℹ The error happened in location book:chapters:2:part.


In file _quarto.yml
(line 25, columns 5--13) property name chapters is invalid
24:   - part: Globals
25:     chapters: chapters/globals/globals.en.qmd
       ~~~~~~~~~
26:   - part: Utilities
ℹ The error happened in location book:chapters:2:chapters.


Stack trace:

In file _quarto.yml
(line 24, columns 5--9) property name part is invalid
23:     - chapters/tutorials/localization.en.qmd
24:   - part: Globals
       ~~~~~
25:     chapters: chapters/globals/globals.en.qmd
ℹ The error happened in location book:chapters:2:part.


In file _quarto.yml
(line 25, columns 5--13) property name chapters is invalid
24:   - part: Globals
25:     chapters: chapters/globals/globals.en.qmd
       ~~~~~~~~~
26:   - part: Utilities
ℹ The error happened in location book:chapters:2:chapters.

    at readAndValidateYamlFromFile (file:///opt/quarto/bin/quarto.js:20470:15)
    at async file:///opt/quarto/bin/quarto.js:72903:26
    at async projectContext (file:///opt/quarto/bin/quarto.js:72737:26)
    at async render (file:///opt/quarto/bin/quarto.js:81779:19)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:81954:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:114968:5)
    at async file:///opt/quarto/bin/quarto.js:114986:9
Error in `quarto::quarto_render()`:
✖ Error running quarto cli.
Caused by error:
! System command 'quarto' failed
Run `rlang::last_trace()` to see where the error occurred.
> 
```

**Comment by RealRichi3** [comment]
@BatoolMM please can you see this.

From the error logs it seems like it doesn't recognize the `part` keyword only when there are multiply `part` used

**Comment by BatoolMM** [comment]
I will look into this and get back to you @RealRichi3 - thank you!

**Comment by RealRichi3** [comment]
@BatoolMM Good morning, please have you been able to review this?

**Comment by BatoolMM** [comment]
Hi @RealRichi3 - when I run `npm run doc:generate include_localized_versions languages="en,ar,es,fr" --source=dist`

I got this error!

```
Error: ENOENT: no such file or directory, scandir '/Users/batool/Desktop/GitHub/JSquarto/src/../dist'
    at Object.readdirSync (node:fs:1437:3)
    at getJSFilesFromDirectory (/Users/batool/Desktop/GitHub/JSquarto/src/index.ts:33:22)
    at /Users/batool/Desktop/GitHub/JSquarto/src/index.ts:66:23
    at Generator.next (<anonymous>)
    at /Users/batool/Desktop/GitHub/JSquarto/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/batool/Desktop/GitHub/JSquarto/src/index.ts:4:12)
    at start (/Users/batool/Desktop/GitHub/JSquarto/src/index.ts:69:12)
    at Object.<anonymous> (/Users/batool/Desktop/GitHub/JSquarto/src/index.ts:242:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
[ERROR] 14:34:12 Error: ENOENT: no such file or directory, scandir '/Users/batool/Desktop/GitHub/JSquarto/src/../dist
```

**Comment by RealRichi3** [comment]
@BatoolMM the error is because we're trying to generate the doc for a typescript project, run `tsc -b` to transpile to js first, before running the command to generate the docs

**Comment by BatoolMM** [comment]
Oh, that's true - I didn't have typescript in this machine - i installed it and did run the TypeScript compiler. it is working now. The only problem is:

```r
babelquarto::render_book(project_dir)
```
We have to define what is the `project_dir` - it gives me this error:
`Error in file.path(path, "_quarto.yml") : object 'project_dir' not found`

**Comment by RealRichi3** [comment]
Ohh, set the project dir to the `/docs` folder in JSQuarto

**Comment by RealRichi3** [comment]
This is how i did mine, but you'll have to run the jsquato command to generate the .qmd files first

```bash
> project_dir <- "/home/richie/Desktop/repos/oscsa/JSquarto/docs"
> readLines(file.path(project_dir, "_quarto.yml"))
 [1] "project:"                                                                   
 [2] "  type: book"                                                               
 [3] "  output-dir: _book"                                                        
 [4] "website:"                                                                   
 [5] "  title: JSQuarto Documentation"                                            
 [6] "  description: Documentation for JSQuarto, a tool for generating JavaScript"
 [7] "    package API reference documentation using Markdown and Quarto."         
 [8] "book:"                                                                      
 [9] "  title: Open Innovation Platform Documentation"                            
[10] "  chapters:"                                                                
[11] "    - index.md"                                                             
[12] "    - part: Globals"                                                        
[13] "      chapters:"                                                            
[14] "        - chapters/globals/globals.qmd"                                     
[15] "    - part: Utilities"                                                      
[16] "      chapters:"                                                            
[17] "        - chapters/functional doc/utilities/constructidentifier.qmd"        
[18] "        - chapters/functional doc/utilities/commentsutil.qmd"               
[19] "        - chapters/functional doc/utilities/components.qmd"                 
[20] "        - chapters/functional doc/utilities/file.qmd"                       
[21] "        - chapters/functional doc/utilities/logger.qmd"                     
[22] "        - chapters/functional doc/utilities/parser.qmd"                     
[23] "        - chapters/functional doc/utilities/writer.qmd"                     
[24] "    - part: Tutorials"                                                      
[25] "      chapters:"                                                            
[26] "        - chapters/tutorials/contributing/improving_documentation.qmd"      
[27] "        - chapters/tutorials/contributing/raising_issues.qmd"               
[28] "        - chapters/tutorials/contributing/raising_pr.qmd"                   
[29] "        - chapters/tutorials/how_to/adding_tutorials.qmd"                   
[30] "        - chapters/tutorials/how_to/optimizing_workflow.qmd"                
[31] "        - chapters/tutorials/how_to/starting_the_project.qmd"               
[32] "        - chapters/tutorials/project_structure.qmd"                         
[33] "        - chapters/tutorials/environment_setup.qmd"                         
[34] "        - chapters/tutorials/changelog.qmd"                                 
[35] "        - chapters/tutorials/localization.qmd"                              
[36] "format:"                                                                    
[37] "  html:"                                                                    
[38] "    theme: cosmo"                                                           
[39] "    highlight: github"                                                      
[40] "    toc: true"                                                              
[41] "    number-sections: false"                                                 
[42] "babelquarto:"                                                               
[43] "  languagecodes:"                                                           
[44] "    - name: en"                                                             
[45] "      text: Version in en"                                                  
[46] "    - name: fr"                                                             
[47] "      text: Version in fr"                                                  
[48] "    - name: ar"                                                             
[49] "      text: Version in ar"                                                  
[50] "    - name: tk"                                                             
[51] "      text: Version in tk"                                                  
[52] "  mainlanguage: en"                                                         
[53] "  languages:"                                                               
[54] "    - en"                                                                   
[55] "    - fr"                                                                   
[56] "    - ar"                                                                   
[57] "    - tk"                                                                   
[58] "lang: en"                                                                   
[59] "title-en: Title in en"                                                      
[60] "description-en: Description in en"                                          
[61] "author-en: Author in en"                                                    
[62] "title-fr: Title in fr"                                                      
[63] "description-fr: Description in fr"                                          
[64] "author-fr: Author in fr"                                                    
[65] "title-ar: Title in ar"                                                      
[66] "description-ar: Description in ar"                                          
[67] "author-ar: Author in ar"                                                    
[68] "title-tk: Title in tk"                                                      
[69] "description-tk: Description in tk"                                          
[70] "author-tk: Author in tk"                                                    
> babelquarto::render_book(file.path(project_dir))
```

**Comment by BatoolMM** [comment]
Hi @RealRichi3 - yes we shouldn't have a hardcoded path in the code like this one `"/home/richie/Desktop/repos/oscsa/JSquarto/docs"` because it will be different for each user.

There is a package called [`here`](https://here.r-lib.org/articles/here.html) that can be used to remove hardcoded path.

```
> babelquarto::render_book(file.path(project_dir))
[ 1/19] index.md
[ 2/19] chapters/globals/globals.qmd
[ 3/19] chapters/functional doc/utilities/constructidentifier.qmd
[ 4/19] chapters/functional doc/utilities/commentsutil.qmd
[ 5/19] chapters/functional doc/utilities/components.qmd
[ 6/19] chapters/functional doc/utilities/file.qmd
[ 7/19] chapters/functional doc/utilities/logger.qmd
[ 8/19] chapters/functional doc/utilities/parser.qmd
[ 9/19] chapters/functional doc/utilities/writer.qmd
[10/19] chapters/tutorials/contributing/improving_documentation.qmd
[11/19] chapters/tutorials/contributing/raising_issues.qmd
[12/19] chapters/tutorials/contributing/raising_pr.qmd
[13/19] chapters/tutorials/how_to/adding_tutorials.qmd
[14/19] chapters/tutorials/how_to/optimizing_workflow.qmd
[15/19] chapters/tutorials/how_to/starting_the_project.qmd
[16/19] chapters/tutorials/project_structure.qmd
[17/19] chapters/tutorials/environment_setup.qmd
[18/19] chapters/tutorials/changelog.qmd
[19/19] chapters/tutorials/localization.qmd

Output created: _book/index.html

ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 12, columns 5--9) property name part is invalid
11:   - index.md
12:   - part: Globals
       ~~~~~
13:     chapters: chapters/globals/globals.en.qmd
ℹ The error happened in location book:chapters:1:part.


In file _quarto.yml
(line 13, columns 5--13) property name chapters is invalid
12:   - part: Globals
13:     chapters: chapters/globals/globals.en.qmd
       ~~~~~~~~~
14:   - part: Utilities
ℹ The error happened in location book:chapters:1:chapters.


Error: Project _quarto.yml validation failed.

In file _quarto.yml
(line 12, columns 5--9) property name part is invalid
11:   - index.md
12:   - part: Globals
       ~~~~~
13:     chapters: chapters/globals/globals.en.qmd
ℹ The error happened in location book:chapters:1:part.


In file _quarto.yml
(line 13, columns 5--13) property name chapters is invalid
12:   - part: Globals
13:     chapters: chapters/globals/globals.en.qmd
       ~~~~~~~~~
14:   - part: Utilities
ℹ The error happened in location book:chapters:1:chapters.

    at readAndValidateYamlFromFile (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:42120:15)
    at async file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82873:26
    at async projectContext (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:82725:26)
    at async render (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:90657:21)
    at async Command.fn (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:90856:32)
    at async Command.execute (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:8437:13)
    at async quarto (file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:127545:5)
    at async file:///Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto.js:127563:9
Error in `map()`:
ℹ In index: 1.
Caused by error:
! System command 'quarto' failed
```
